### ISSUE TITLE
iphoneで音声再生できない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_blog#10]
サンプリングレートが24000になっていて、これに未対応なブラウザでは音声が再生できないようです。
ffmpeg等で適当にリサンプリングすることもできますが、gatsbyにもしリサンプリング機能などがあるならそっちを使えると最高かもです。

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/voicevox_blog/pull/35

で修正されたはず

**Comment by Hiroshiba** [comment]
うーん、flacにしてもなぜか再生できませんね･･･
ということで再openしてみます。

**Comment by PickledChair** [comment]
調べたら、関係しそうな情報を見つけたので報告します（門外漢なので見当違いの情報でしたらすみません！）。

再生できない理由は、`"canplaythrough"` イベントが発火せず、

https://github.com/VOICEVOX/voicevox_blog/blob/e7b858abd6becb041d0cdcca75a16720cd61c28c/src/components/playButton.tsx#L50

で登録している `onReady` 関数が呼ばれないことが原因だと思いますが、この `"canplaythrough"` イベントは、iOS の Safari では、オーディオファイルがサポートしているオーディオ形式であるかどうかに関わらず、放っておくと発火しないようです。`audio.load()` を呼ぶと発火するようになるらしいです（iOS Safari 以外の環境では放っておいてもロードされるらしいです。混乱する仕様ですね😅）。

参考： https://stackoverflow.com/questions/49792768/js-html5-audio-why-is-canplaythrough-not-fired-on-ios-safari

React では、`useEffect` の中でこれを呼ぶと良さそうです（以下のリンク先は audio ではなく video の例ですが、おそらく同じ対処が可能な気がしています）。

参考： https://zenn.dev/pale_delphinium/articles/3b2fa470697374

**Comment by PickledChair** [comment]
マージ後、自分の iPhone, iPad では音声再生できていたので大丈夫そうでした。閉じるのを忘れていたのでクローズします！

**Comment by Hiroshiba** [comment]
さっき確認しました、ありがとうございます！！
