### ISSUE TITLE
ボイボ寮 のページのヘッダーがスクロールしないと利用できない

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox_blog#100]
他のページだとヘッダー固定なのに、ボイボ寮 のページのヘッダーがスクロールしないと利用できない（仕様？）になっている。

問題提起のため立てます。

**Comment by Hiroshiba** [comment]
一応仕様で問題ないと感じているのでcloseします。
提案募集中です。

**Comment by sevenc-nanashi** [comment]
![image](https://user-images.githubusercontent.com/59691627/195203348-c231af5e-ede7-4ccf-a101-34380efb6cc0.png)

こんな感じに、VOICEVOXの下にヘッダーと同じメニュー（ダウンロード以外）をつけるのはどうでしょう？
スマホの表示をどうするかが問題になりそう

**Comment by Hiroshiba** [comment]
おーーなるほどです！！
