### ISSUE TITLE
【サイト改善案】ユーザーマニュアルやユーザーサポートの動線整備

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox_blog#12]
## 内容
ページの改善案です。

現在、製品ページはありますがユーザーマニュアルやユーザーサポートがなく、利用ユーザーのトラブルシューティングなどに少々不親切感があります。
ユーザーマニュアルやユーザーサポートのページを作るのはいかがでしょうか？

参考：
- [A.I.VOICE Editor ユーザーマニュアル](https://aivoice.jp/manual/editor/index.html)
- [TOP A.I.VOICE™ ユーザーサポートサイト](https://aivoice.jp/member/)

## メリット

- 使い方はユーザーマニュアルを確認すればユーザーとして使いやすくなる。
- 基本トラブルシューティングやFAQを書いておくことで、簡単なことは解決しますし、改善しない場合最終的にお問合せ先としてGitHubなどでissueなどでお問合せすればいいという問題切り分けに役に立つ

## デメリット

- ある程度の問題を解決できるようにするため、ある程度トラブルシューティングを網羅の必要

## その他
上記のリンクのページを参考に作っていいなら作りますけどどうしますか？

**Comment by takana-v** [comment]
一応ユーザーマニュアルっぽいものは既にあります。
（ダウンロード→使い方で確認できます）
しかし場所が分かりにくいので改善の余地がありそうです。
また、使っている写真や内容も古くなっているので、使い方のページを更新するのもいいかもしれません。

ちなみに使い方のページは以下のマークダウンファイルになっています。
https://github.com/VOICEVOX/voicevox_blog/blob/master/src/markdowns/howToUse.md
これは、VOICEVOX本体の使い方のページと同じもの（のはず）です。
https://github.com/VOICEVOX/voicevox/blob/main/public/howtouse.md

**Comment by Apple-Yuki** [comment]
@takana-v 
今見てみましたが、ダウンロード押してからのマニュアル系表示されるのはわかりづらいので、せめてトップページのダウンロードボタンの下に置けないのかな...とか思ってみたりしました。

**Comment by Hiroshiba** [comment]
たしかに使い方への導線はわかりづらい気がします。

ファーストビューはボタン増やしたくないので、この２つめのダウンロードボタンの横辺りに「使い方」ボタンがあると良いのかなと感じました。
![image](https://user-images.githubusercontent.com/4987327/146583619-286a88d9-f5ca-4da6-a3c8-2e92eb5ddd83.png)

あと、今はモーダル表示ですが、新しく使い方ページを作ってそちらでmarkdownをレンダリングし、ホームページからリンクするのが一番良さそうに感じます。

---

FAQも仰るとおり必要だと思います！

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
一応、Mac版のリリースに向けてMac版のユーザーガイドを作ってみました。
https://github.com/Apple-Yuki/voicevox_blog/blob/master/src/markdowns/Mac-howtouse.md

**Comment by Hiroshiba** [comment]
なるほどーーー　起動方法あたりがmac版とwin版で異なるから別ファイルにしている、ということですね。
たしかに使い方の記載が変わってくることに今気づきました。

mac版とwin版で２つ管理するのはメンテナンスコストが高くなってしまい、かつ片方に適用し忘れることもありそうな気がします。
画像差し替えは一旦なしの方向にして、macの記載を追加し、voicevoxリポジトリにプルリクエストを送って頂けるととても助かります！！
https://github.com/VOICEVOX/voicevox/blob/main/public/howtouse.md

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
macの記載を追加し、voicevoxリポジトリにプルリクエストをお送りしました。

**Comment by Apple-Yuki** [comment]
@Hiroshiba @takana-v 
ちなみに気になったのですが、
https://github.com/VOICEVOX/voicevox_blog/blob/master/src/markdowns/howToUse.md
のマークダウンのページはポップアップではなくgithub page単体のページとしては存在しない感じですかね？

**Comment by Hiroshiba** [comment]
はい、現状単体ページとしては存在してないです。
作りたいとは思いつつ、時間がなくてちょっと手が出せてない感じです…。

**Comment by Hiroshiba** [comment]
実装されたのでcloseします！
