### ISSUE TITLE
ヘッダーがフラッシュするのを抑制したい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_blog#125]
## 不具合の内容

ヘッダーはコンポーネントが同じなのでページ遷移時にフラッシュしないはずなのですが、なぜか点滅します。
gatsbyの仕組み的に再読み込みは走らないはずな気がするのですが、なぜフラッシュするのかが気になっています。

### 再現手順

利用規約からQ&Aに移動したりするとわかりやすい

### 期待動作

DOMが置き換わらない

## その他

ヘッダーが原因なのかわからない。。。
別のなにかの原因になっているかもと思っています。

- https://github.com/VOICEVOX/voicevox_blog/issues/124

**Comment by k-chop** [comment]
![image](https://user-images.githubusercontent.com/241973/213841575-eec2a9e9-bd40-4a4d-b3c4-ad77762578aa.png)
このcssが原因のようです

**Comment by k-chop** [comment]
devtoolsでこのcssを取り外したらちらつきはなくなりました！！
（navigate利用 && popState関連のコードはコメントアウト済み）

![qwe](https://user-images.githubusercontent.com/241973/213841655-9a9327dc-1bbe-476e-86ae-f1a6817a9f3b.gif)

**Comment by Hiroshiba** [comment]
なーーーーーーーーるほどです！！！！！！
かなり調べたのですが、Gatsby側の課題だと勝手に思い込んで遠回りしていました･･･。ありがとうございます！！！

アニメーションに関してはなるほどです、そこは仕方ないのかもですね！
pluginもありそうだというのは知っていたのですが、まあ逆に言うとそれを介さないとダメな感じかもですね。

フラッシュに関してはこのCSSanimationの適用をちゃんと条件付ければ良さそうに感じました。
ありがとうございます！！！

**Comment by Hiroshiba** [comment]
こちら、とりあえずキャラ移動のアニメーション側をどうするかはさておき、フラッシュを抑制するのをやってみようと思います！
