### ISSUE TITLE
Q&Aページを作りたい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_blog#15]
操作に関してのよくあるQ&Aや、商用利用に関する問い合わせのQ&Aなどをまとめたページを作りたいです。
issue作ったついでに、Q&Aに乗せたいことをもこのissueにメモしていきたいと思います。

こちらのissueからの切り出しになります

- https://github.com/VOICEVOX/voicevox_blog/issues/12#issue-1083190061

* ソフトウェアに関して
  * （使い方のQ&Aをコピペ）
* 利用に関して
  * 別のキャラクターの声に使ってもいいですか
    * 利用規約でNGになっていなければ大丈夫です
  * 電話音声など、音声のみを使いたい場合のクレジット記載はどうすればよいか
    * ずんだもん・四国めたんに関しては商用ライセンスがあるので案内
    * それ以外は冒頭か最後に音声クレジットを入れてもらう
  * webサーバーを用いる仕組みですが、そのクラウドサーバーの仕組みを教えてください
    * ご利用のパソコンにローカルでサーバーが起動するだけなのでクラウドではない
    * ネットワーク通信を切りながらソフトウェアが使えると思うので試してもらう

**Comment by Apple-Yuki** [comment]
@Hiroshiba 

こう書いてあげれば、ちょっと親切なFAQになると思いますよ。🎉

- 別のキャラクターの声に使ってもいいですか
    -  キャラクターの利用規約でNGになっていなければ大丈夫です。音源利用規約は以下の通りです。
        - [ずんだもん、四国めたん ](https://zunko.jp/con_ongen_kiyaku.html)
        - [春日部つむぎ](https://tsukushinyoki10.wixsite.com/ktsumugiofficial/利用規約)
        -  雨晴はう
        -  [波音リツ](http://canon-voice.com/kiyaku.html)

**Comment by Apple-Yuki** [comment]
いろんなソフトウェアのFAQを参考にFAQのたたき台的なものを作ってみました。
https://github.com/Apple-Yuki/faq_voicefox/blob/main/faq_memo.md

**Comment by Hiroshiba** [comment]
良いですね！

せっかく作って頂けるなら、よりユーザーにとって嬉しそうなFAQになっていると良いかなと思いました！
その疑問を感じた人は本当にそのFAQを読むのか、本当にその疑問を持つ人はいるのかを考えて書くのが良いのかなと思います。

例えばこちらのQですが

> Q.Webサーバーを用いる仕組みですが、オフラインのパソコン、Macで利用できますか？

`Webサーバーを用いる仕組みですが`という前置きが必要な人はめったにいなそうなのと、「オフラインのパソコンで利用できますか？」と被るので、消せそうです。
また「macで利用できますか？」は、その前の質問（MacのOSに対応していますか？）と被るので疑問を持つ人はいないことと、オフラインのパソコンにmacは含まれるので、省けると思います。
となると、Qはシンプルに

> オフラインのパソコンで利用できますか？

となりそうです。

他にも

> Q.歌わせることは可能ですか？

「テキスト音声合成ソフトウェア」でこの疑問を持つ人はいないと思います。

> Q.話すスピード、間の調整はできますか？

これを知りたい人は、使い方などを見るはずです。
FAQにこれを書くと、使い方の全てをFAQに書く必要が出てきます。

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
ご指摘いただいた部分を削除や変更しました。
https://apple-yuki.github.io/VOICEVOX-FAQ-/

**Comment by Hiroshiba** [comment]
良さそうです！
文量をあと1/4くらい削りたいかもと感じました。

サイトのコードはreact（とgatsby）なのですが、もし書ければぜひ個別ページ作成のプルリクエストがほしいです…！！
ボイボ寮ページが個別ページなので参考になるかもです。（domitoryでコード検索すると関連のものがヒットするはず）

gatsbyはよくわかってなくて、あまり使いこなせてません…

**Comment by Apple-Yuki** [comment]
@Hiroshiba ボイボ寮ページはどこに在りますか？

**Comment by Hiroshiba** [comment]
質問の意図がつかめていないかもですが、こちらでしょうか？
https://voicevox.hiroshiba.jp/dormitory/

**Comment by Apple-Yuki** [comment]
@Hiroshiba 
そちらのページのソースを参考に
今、こんな感じのデザインに今変更してるのでできたらスタイルとか埋め込もうと思います。

https://apple-yuki.github.io/VOICEVOX-FAQ-/demo

**Comment by Hiroshiba** [comment]
おお、いいですね！！

ただ、ページはreact製じゃないとおそらくマージできませんが、認識は合っていますか・・・？

**Comment by Apple-Yuki** [comment]
@Hiroshiba 

そもそも、使ってるのがCSSとjqueryなので環境依存はしないですよ。

そのなかにソース丸がきすれば大丈夫な気もします。

**Comment by Hiroshiba** [comment]
なるほど・・・！
