### ISSUE TITLE
提案: メニューバー(ヘッダー)の追加

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox_blog#16]
ボイボ寮や、Q&Aページの追加、利用規約の分離等々、ページが増えていく傾向にありそうです。
ヒホさんは`ファーストビューはボタン増やしたくない`と考えているよう(https://github.com/VOICEVOX/voicevox_blog/issues/12#issuecomment-996893241 )ですが、主要なページに関してはメニューバーを作り、そこに載せてあげることでページへの導線を作った方がよいのではと考えます。
ユーザー的には`とりあえずVOICEVOXのHPに来れば、見たいものが大体見られるといった状態`の方が望ましいのでは、と私は思います。
また、ページ全体のアクセシビリティの向上にもつながると思います。
ヒホさんの考えには反するかもしれませんが、メリットデメリット次第では、メニューバーがあった方が良い効果をもたらすのではないかと思い、本提案をするに至りました。

**Comment by Hiroshiba** [comment]
ヘッダー、いいと思います！

言及されているコメントの意図は、ダウンロードボタンが他のボタンに紛れるのがいまいちかもと感じたためです。
ヘッダーであれば、求めてる人以外からはあまり意識に入らないので良いと思います。

ちょっと今のファーストビューのデザインとコンフリクトしそう（帯が二重になって変になりそう）なので、そこだけなんとかしたいかもです。

**Comment by Hiroshiba** [comment]
ヘッダーに関して考えてみたのですが、VSCodeもChromeのページも、右上にダウンロードボタンがずっと表示されるデザインだったので、真似してみたいと思います。

bulmaのヘッダーがこれなので、そのまま使う感じが良いかなと思いました。
![image](https://user-images.githubusercontent.com/4987327/147413275-2cffa364-b3ab-4a16-a594-a88d421ebc0c.png)

最初からヘッダーを表示するかですが、デザインが狂うようであればちょっとスクロールしたら表示というのもありかなと思いました。

**Comment by Hiroshiba** [comment]
ちょっとイマイチかもですがとりあえずヘッダーを付けられたのでcloseします！


![image](https://user-images.githubusercontent.com/4987327/147420361-6966f117-966f-498b-a6ed-b02a0696ec73.png)
