### ISSUE TITLE
Next.js に移行する

### ISSUE THREAD

**Issue by raa0121** [VOICEVOX/voicevox_blog#189]
## 内容

Gatsby から Next.js に移行する

### Pros 良くなる点

- GraphQL から離れられる

### Cons 悪くなる点

既存の PR も対応する必要がある

### 実現方法

参考URL: https://nextjs-ja-translation-docs.vercel.app/docs/migrating/from-gatsby

**Comment by Hiroshiba** [comment]
@raa0121 ありがとうございます！！！　ぜひぜひ！！！

あ、もしよかったらdraft PRにしておくというのはどうでしょうか？ 👀 
他の方が今どんな感じなのかを見れるのと、Next.jsはどんな感じの雰囲気なのか僕もちょっと見れて嬉しいかなと思った次第です！
もしNext.jsに超強い方が現れたときにすごく良い設計の提案をもらえたりもする･･･かも･･･？

**Comment by nix6839** [comment]
今作業している方がいなければ私が進行してみてもいいですか？

そして、他のフレームワークに対して開かれているのかも気になります。
[SolidStart](https://github.com/solidjs/solid-start)というものを使ってみたいので、下に長所と短所を並べてみます。

## Pros
- Next.jsが使用するReactに比べてSolidStartが使用するSolidJSは、はるかに速い性能とはるかに小さい基本バンドルサイズを持っています。 これにより、ユーザがより速いローディング速度を感じることができます(ただし、この部分はメタフレームワーク(Next.js, Solid Start)によってプレレンダリングされるため、体感が大きくないことがあります。) 参考: https://ogzhanolguncu.com/blog/react-vs-solid/#benchmarks
- Reactと同じJSX文法を使うため、他のフレームワーク(Svelte、Vueなど)に比べて移行が容易です。
## Cons
- メインテイナーが深く知る必要はありませんが、ある程度は新しい学習が必要です。
- Next.jsに比べて少ない生態系です。 それによる寄与者の減少と開発の不便さ(この部分は私が甘受することができます)

どちらにしても、この作業を私が進めてみたいです。 ご意見を自由にお願いします。

**Comment by Hiroshiba** [comment]
@nix6839 
申し出ありがとうございます！　いくつか相談できればと思います！！

SolidStartについて調べてみました。
たしかにSolidJS含めエコシステムが未成熟なのが気になりますが、記法はほぼReactなので、SolidStart独自の特殊な機能をあまり使わなければそこまで問題にならないように感じます。
将来また別のフレームワークに乗り換えればOK。
Reactに比べ簡単に高速なウェブフロントを作れそうなのも好感触です。

今のVOICEVOX blogのwebページをどの程度再現できるか、再現できない場合は妥協案はあるのかを少し考えてみたいです。
SolidStartを使う場合に課題となりそうな点を挙げてみます！

* 大量なキャラクター画像リソースの読み込み
	* 今はgatsbyの[GraphQLを使ってファイル名をgrepして静的に読み込んでいます](https://github.com/VOICEVOX/voicevox_blog/blob/master/src/hooks/useDetailedCharacterInfo.ts)
	* 同じような仕組みがおそらくSolidStartに無いので、代案を考えておくとスムーズかもしれません
	* もっとも、これはNext.jsにも無いのですが･･･。
* URLが変わる静的ページ作成
	* VOICEVOX公式ページは[キャラクターごとにページ](https://voicevox.hiroshiba.jp/product/shikoku_metan/)を作っています
	* `src/pages/`に新しくファイルを作ることなく、characterIdに応じたキャラクターごとのページを静的に作ることはできそうでしょうか。
	* （solid-routerを使えばできそう･･･？）
* 画像の効率的な読み込み
	* gatsbyやNext.jsでは、画面サイズに応じてあらかじめ画像サイズ等を縮小しておく機能があると思います
	* SolidStartにはこの仕組みはありそうでしょうか
	* ない場合、いろんなサイズのキャラクター画像を用意する覚悟が必要かもしれません

他にも、気にしておくと良いポイントがあるかもしれません。思いついたら書きます！

もし大丈夫そうなら、全体的にポジティブに感じています。
Viteが使える・Gatsbyよりわかりやすい・ReactのuseMemoの難しさがなくなる・早そう、そしてなにより @nix6839 さんがいらっしゃること！

まとまりきっていませんが、これが今の僕の意見です！

**Comment by nix6839** [comment]
比較表を下に作ってみました。 また、お話しいただいた部分を見ながら[Astro]も適していると思い、その部分も入れました。

|                                                                  | [Gatsby]                                                                                      | [Next.js]                                                                                                                    | [SolidStart]                                                                               | [Astro]                                                                                 |
| ---------------------------------------------------------------- | --------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------- |
| JS UIフレームワーク（React、SolidJS等の）を使用できるか？        | O(React)                                                                                      | O(React)                                                                                                                     | O(SolidJS)                                                                                 | [O(オプションである)](https://docs.astro.build/ja/concepts/islands/)                    |
| 画像の効率的な読み込み                                           | [O](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/)         | [O](https://nextjs.org/docs/app/building-your-application/optimizing/images)                                                 | X[^1]                                                                                      | [O](https://docs.astro.build/ja/guides/images/)                                         |
| 大量なキャラクター画像リソースの読み込み                         | [O(with GraphQL)](https://www.gatsbyjs.com/docs/graphql/)                                     | X[^2]                                                                                                                        | [O](https://vitejs.dev/guide/features#glob-import)                                         | [O](https://docs.astro.build/ja/guides/imports/#astroglob)                              |
| URLが変わる静的ページ作成                                        | [O](https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#collection-routes) | [O](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#dynamic-paths-getstaticpaths)       | [O](https://docs.solidjs.com/solid-start/building-your-application/routing#dynamic-routes) | [O](https://docs.astro.build/ja/guides/routing/#dynamic-routes)[^3]                     |
| マークダウン支援                                                 | [O](https://www.gatsbyjs.com/docs/reference/markdown-syntax/)                                 | [O](https://nextjs.org/docs/app/building-your-application/configuring/mdx#deep-dive-how-do-you-transform-markdown-into-html) | X[^4]                                                                                      | [O](https://docs.astro.build/ja/guides/markdown-content/)                               |
| 学習費用                                                         |                                                                                               | ほとんどなし                                                                                                                 | 高級用法を使用しない限りほとんどなし                                                       | 完全に基礎的な部分(TypeScript、CSS、HTMLなど)を除いては最初から学ばなければならない[^5] |
| パフォーマンスとバンドルサイズ（1に近いほどVanilla JSに近い性能） | 6                                                                                             | 6                                                                                                                            | 3                                                                                          | 1~?[^6]                                                                                 |


[^1]: [sharp]を直接使用して実装することができます。 他のフレームワークも内部的にはイメージ最適化に[sharp]を使用します。
[^2]: [glob] などを使って実装することができます。
[^3]: この部分は可能ですが、Astroは基本的にSPA Router(React Router、Solid Routerなどの)を使わないので、他のフレームワークのように自然に切り替わることは調べてみる必要があると思います。 [View Transition](https://docs.astro.build/ja/guides/view-transitions/)あるいは[Astro Island](https://docs.astro.build/ja/concepts/islands/)を利用してSPA Routerを注入して達成できると思われます。
[^4]: 少しの作業を経て使用できます。 投稿を参考（投稿にはMDXについての説明がありますが、マークダウンのサポートにもなると予想）: https://frde-me.fly.dev/notes/solid-start-markdown
[^5]: これは私の主観的な部分ですが、非常に簡単なので問題ないと思います。
[^6]: Astroは基本的にJS UIフレームワークではないので流動的です。

整理した後の私の学習費用を考慮しない推薦順位は、Astro(+Solid)、Next.js、SolidStart、Astro(+React)の順です。(SolidStartの基本サポート機能が思ったより足りなかったです···)

しかし結局マイグレーション後にコードを一番多く修正する方は @Hiroshiba さんなので @Hiroshiba さんの意見が一番重要だと思います。 ご意見を自由にお願いします :)

[Gatsby]: https://www.gatsbyjs.com/
[Next.js]: https://nextjs.org/
[SolidStart]: https://start.solidjs.com/
[Astro]: https://astro.build/
[sharp]: https://sharp.pixelplumbing.com/
[glob]: https://github.com/isaacs/node-glob

**Comment by Hiroshiba** [comment]
精査ありがとうございます！！
Astroのドキュメントを少し眺めてみました。
良さそうに感じています！
念の為に問題点がありそうか、もう少し考慮したいです。

**Comment by Hiroshiba** [comment]
@nix6839 すみません、お待たせしました！！

Astro、試してみるのありだと思います！！
学習コストは低くありませんが、考え方が分かりやすいので1回実装してしまえば継ぎ足しは簡単そうです。
v3から必要な機能が一通り揃っていると感じます。
静的サイトを作るのにかなり適しているフレームワークだと感じます！
このフレームワークがどれくらい長続きするかが若干不安ですが、まあこればかりは仕方ないかなと。

一通りドキュメントを眺めてみましたが、MPA（Multi Page Application）だということが問題になりそうに思いました。
ユーザーがいろんなページを見て回る際にどれぐらいブラウジングが不便か気になります。
ですがこれはやってみないと分からない点だと思います。

まずは一通り必要そうな機能が揃っていることを確かめるのはどうでしょうか！
その場合、とりあえず[メインページ](https://github.com/VOICEVOX/voicevox_blog/blob/master/src/pages/index.tsx)と[キャラクター個別ページ](https://github.com/VOICEVOX/voicevox_blog/blob/master/src/pages/product/%7BCharacter.characterId%7D.tsx)が適しているかもしれません。
2種類の異なるレイアウト、scss、大量のデータのロードとデータ構造への当てはめ、ビルド時に決まる URL、ダークモード・ライトモードの両対応、[SEO](https://github.com/VOICEVOX/voicevox_blog/blob/master/src/components/seo.tsx)などなどが揃っているためです。

このissueはNextjsなので、もしAstroで挑戦してくださるのであれば @nix6839 がやりやすいようにissueを作っていただければと思います！
例えば、箇条書きでチェックリストを作って1つずつ埋めていくとかやりやすいんじゃないかなと思います。
もし途中で事情が変わった際も、できているところまで見てみたいです！！

不明な点があれば何でもお聞きください！！

**Comment by nix6839** [comment]
> このissueはNextjsなので、もしAstroで挑戦してくださるのであれば @nix6839 がやりやすいようにissueを作っていただければと思います！

イシューの代わりにドラフトPRを開いて、そこで作業を進めてもよろしいでしょうか？

**Comment by Hiroshiba** [comment]
@nix6839 draft PRでもokです！！

**Comment by Hiroshiba** [comment]
@nix6839 こんにちは！　その後調子はいかがでしょうか？ 👀 

僕もAstroに興味があり、実際にいくつかのページを試しに作ってみようと考えています。
とりあえずforkしたリポジトリで試すつもりです。

そこで、もし @nix6839 さんがかなり進めてくださっているなら、そこから制作する、もしくは続きを作るのも良い手段かもしれないと考えています！
もしよければリポジトリなどを教えていただければ･･･！

また途中で難しくなった点などがあれば、そちらもお聞きしてみたいです。
そこは僕もいずれ大変なことになると思うので･･･。

**Comment by Hiroshiba** [comment]
こちらのタスクに関して、Astro化が完了したのでmainにマージしてデプロイしたいと思います！
issueタイトルが異なってややこしいので、別でissueを作りたいと思います！

@raa0121 さんと @nix6839 さんのおかげで検討を進めることができました、ありがとうございました！！！

**Comment by nix6839** [comment]
私はこれまで韓国の軍隊訓練所にいたので、電話を見ずに通知を確認しました。 今は訓練所が終わって軍隊の中ですがラップトップを持って来ることができず、進行中だった作業物は見えないと思います。  （見せてもらえても今は意味がありませんね。） 作業を終えて行きたかったのに急に引っ張ってくるのでコメントも残せませんでした。

**Comment by Hiroshiba** [comment]
軍隊訓練所にいらっしゃったとは知らず、勝手に作業を進めてしまってすみませんでした 🙇 
今はまだお忙しいかもしれませんが、落ち着かれましたらまた一緒になにか作れると嬉しいです！

**Comment by nix6839** [comment]
いいえ、むしろこちらこそお話できずに来て申し訳ありません。 私が軍隊から出る頃、voicevoxがどれだけ発展しているか今から楽しみです！
