### ISSUE TITLE
ソングページ：トークページにあるOSSとかの案内を追加

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_blog#204]
## 内容

ソングページ内でもせっかくなのでオープンソースへのリンクなどを案内したいです。

### 実現方法

トーク側には全く同じものがあるので、それをコンポーネントに切り出して流用するのが良さそうです。

ただトーク側は白基調、ソング側は黒基調なので見た目が合わないはずです。
他のコンポーネントでもたまにある`isDark`引数を追加して両対応するのが良いかなと。

あと多分横幅もずれてるのですが、これはちょっとbulmaの知識が必要なのでめんどうかもです。
`is-max-desktop`的なクラスがついてると思うので、それを入れ替えるたらできたりします。
けどまあ置いといてくださったら僕がちゃちゃっとやっちゃいます！

**Comment by jdkfx** [comment]
@Hiroshiba 
こちらのIssueについて、提案があります。
以下の画像のように、トークとソング画面で説明を記述している部分についての幅を統一したいと考えております。

![トーク](https://github.com/VOICEVOX/voicevox_blog/assets/40142697/7e5e45bb-a35e-4d53-b8e9-953cb6de04f5)
![ソング](https://github.com/VOICEVOX/voicevox_blog/assets/40142697/1df07896-321d-489a-b673-fe69bb393269)

現状のハミングについて説明している箇所の幅を設定しているクラスは`explain-humming`で、調べてみた限りでは、このハミングの説明をしている箇所でしか使用されていないため、
```
          {/* explain-hummingをis-max-desktopに変更 */}
          <div className="container is-max-desktop"> 
            <h2 className="title">ハミングとは？</h2>
            <p>
              喋り声のデータを用いて音声ライブラリを作成し、
              歌えるキャラクターに歌い方を倣うことで、
              キャラクターの喋り声に近い声で歌える機能です。
            </p>
            <p>キャラクターによっていろんなスタイルで歌うことができます。</p>
          </div>
```
とすることで、コンポーネント化したオープンソースへの案内と同じ幅に設定することができます。

PRも作成することが可能で、もしよろしければPRを出してもよろしいでしょうか？
