### ISSUE TITLE
VOICEVOX Songはフリーソフトウェアではない

### ISSUE THREAD

**Issue by nohimazin** [VOICEVOX/voicevox_blog#220]
## 内容

VOICEVOX Songのホームページには
「商用利用可能な
フリーソフトウェア」と記載されているが
フリーソフトウェアとは「そのソフトウェアを、実行、コピー、配布、研究、変更、改良する自由を利用者が有するもの」なので完全に製品版VOICEVOXの利用規約と矛盾している
参考情報 https://www.gnu.org/philosophy/free-sw.ja.html

### 実現方法

「フリーソフトウェア」をフリーウェアなどの
他の言葉に変える

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
自由ソフトウェアの方ではなく、こっちのフリーソフトのつもりですね！
https://ja.wikipedia.org/wiki/%E3%83%95%E3%83%AA%E3%83%BC%E3%82%A6%E3%82%A7%E3%82%A2

調べた感じ、いろいろ言葉が変わってきていて、今は意味が重複していそうな雰囲気を感じました。
https://kotobank.jp/word/%E3%83%95%E3%83%AA%E3%83%BC%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2

ややこしければ「フリーソフト」でも良いかも。他のものと文字数が違ってデザインが少し崩れるので、良い塩梅のものが思い付けると嬉しそうです。
![image](https://github.com/user-attachments/assets/4e0fd844-475a-4252-8e95-850cde925a26)

**Comment by qryxip** [comment]
私も「フリーソフトウェア」はベストではなさそうな気がします。"free software"だったらFSF (Free Software Foundation)が定義している"free software"の方がむしろ(かなり)強いと思いますし、未来永劫日本語話者に対してだけドキュメントを書くというのでなければ考え始めてもよいような気がします。

代替としては、 @nohimazin が提案している**フリーウェア** (_freeware_)が最も誤解を生まないかなと。フリーソフトとフリーウェアのどっちが日本語として普及しているのかについては… 正直よくわからない、けどフリーソフトという言い方すら下火になっている現代なら実はどっちも変わらないんじゃないかという気もします。

---

言い回しの話だと、「VOICEVOXはオープンソース」（「開発はOSSとしてされている」とかではなく）とかの方がやばそう。まあ今から「燃える」シナリオはあまり思い浮かびませんが…
(FS/OSSという概念に対して信念と帰属意識を持つ人が、まずVOICEVOXがどういうソフトウェアなのかを把握し、把握した上で戦闘態勢で突っ込んできて、その人が戦場として選ぶ場がここのissueとかではなく𝕏とかで、同調する人が多数出現し、かつこちらが対応をしくじって追加の話題性を提供してしまう、くらいの条件が必要そう)

**Comment by Hiroshiba** [comment]
デザイン的に問題ない形だと、パッと思いつくのは「フリー歌唱ソフト」とかですかねー。
一番右のとこの「歌唱AI」と字面が被っちゃうけど･･･。

![image](https://github.com/user-attachments/assets/446cc52c-747b-4918-b18e-236e8edeb899)

**Comment by Hiroshiba** [comment]
うーーーーーーん
一旦フリーソフトで行きたいと思います！！
