### ISSUE TITLE
Download Bug　https://voicevox.hiroshiba.jp/

### ISSUE THREAD

**Issue by ckjpn** [VOICEVOX/voicevox_blog#231]
Download Bug　https://voicevox.hiroshiba.jp/

Mac > CPU(Intel) > インストーラー

これは選ぶとダウンロードはできませんでした。

けれども、最初はMac > CPU(Apple) > インストーラー　を選んで、その後CPU(Intel)を選んだら、ダウンロードはできた。

先週も同じことになった。

**Comment by sevenc-nanashi** [comment]
（自分で試して再現しました）
エラーはないですね。CPUとかのボタンを押さないとダウンロード出来ない、だと思います。

https://github.com/user-attachments/assets/7f6e5825-7f58-4e67-a916-9b070eed0d9e

**Comment by Hiroshiba** [comment]
あーーーーーなるほどです！！！！！！
おそらく表示はちゃんとフォールバックされてるけど、ダウンロード対象側と合わなくなっちゃってますね！！！

ちょっとあとで見ておこうと思います、ありがとうございます！！！
