### ISSUE TITLE
Linux 向け Zip 版のダウンロードリンクが CPU・GPU 版ともに CPU 版のリンクを指している

### ISSUE THREAD

**Issue by PickledChair** [VOICEVOX/voicevox_blog#41]
https://github.com/VOICEVOX/voicevox/issues/635 の報告で気づいたのですが、Linux 向け Zip 版のダウンロードリンクが以下のように CPU・GPU 版の両者で同じになってしまっています。

https://github.com/VOICEVOX/voicevox_blog/blob/f935f7f7930a21e342d90e929cfa9963cbcb0183/src/components/downloadModal.tsx#L30-L33

報告の通り、これは CPU 版へのリンクになっていました。GPU 版（上）のリンクの方を直す必要があると思います。

**Comment by Hiroshiba** [comment]
修正しました！　連絡issueありがとうございます！
