### ISSUE TITLE
提案・更新：使い方のページとアプリ内の使い方との情報に差がある（ページ側が古い）

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox_blog#45]
アプリ内の使い方のページとホームページでの情報の差があります。
更新が必要か、以前お話ししていたFAQ分ける際に更新するか一応確認したかったのでイシュー立てました。

**Comment by takana-v** [comment]
- https://github.com/VOICEVOX/voicevox/issues/643

個人的にはこちらのIssueを解決し、blogは分離されたmdファイルを参照するように変更するのが良いと思いました。

**Comment by Hiroshiba** [comment]
あ、 @.takana-v さんが参照されているissueでは、全体構成等の移行だけを考えていました！
たしかに使い方なども`voicevox_resource`とかに分けたほうが良さそうな気がします。

個人的には @Apple-Yuki さんが仰っている情報の差の内容を知りたいかもです。
アプリ側の最新版の使い方は、製品版の最新版とは違って未リリースのものも含まれているので、この点に関してはホームページと情報がずれているのは意図的です。
もしそれ以外で情報の差があれば問題だと思います。

**Comment by Hiroshiba** [comment]
こちらどうでしょう👀　@Apple-Yuki

**Comment by Hiroshiba** [comment]
大丈夫そうなのでcloseします。
