### ISSUE TITLE
heightの短いページに対して、footerが最下部に存在しない

### ISSUE THREAD

**Issue by AsPulse** [VOICEVOX/voicevox_blog#48]
[https://voicevox.hiroshiba.jp/term/](https://voicevox.hiroshiba.jp/term/)のようなページを、高さの大きいブラウザで開くと発生します。

フッターがコンテンツの最下部についてきてしまい、ブラウザの最下部との間に隙間が生じています。

実装方法は考えついているのでそのうちPRを出したいと思いますが、あらぬところに影響が出てきそうなので慎重に行いたいです。

**Comment by Hiroshiba** [comment]
確かに見栄えが悪そうですね…。
PRありがとうございます、お待ちしております！！

**Comment by Hiroshiba** [comment]
マージされたのでcloseします。ありがとうございました！！
