### ISSUE TITLE
AndroidのChromeでトップページの音声サンプルを切り替えられない

### ISSUE THREAD

**Issue by so-c** [VOICEVOX/voicevox_blog#93]
■現象
AndroidのChromeだと[トップページ](https://voicevox.hiroshiba.jp/)の音声サンプルのスタイルを切り替えられない

■再現手順
1. トップページを表示する
2. スタイルをタップし、スタイル一覧を表示する
3. 再生させたいスタイルを選択する
4. 初期スタイルのまま表示が変わらない。再生ボタンを押してもやはり初期素タイルが再生される

■環境
Chrome 106.0.5249.65, 106.0.5249.79 (アプデしても改善せず）
OS Android 9

■備考
環境不明ですが同じ症状の方が他にも
https://twitter.com/nanami_eiko/status/1576205893246427136

iPhoneのChromeでは切り替わるようです
https://twitter.com/tuina_FanBook/status/1576202812303998976

**Comment by Hiroshiba** [comment]
@so-c issue作成ありがとうございます！
androidを持っていないため再現できず困っています･･･。
画面のスクショや、横持ちにした場合どうか、可能であればHTMLの対比（要素はあるけど見えないのか、そもそも要素がないのか）などの調査をお願いできないでしょうか🙇

**Comment by qryxip** [comment]
私もAndroidを持っているのですが、ChromeとFirefoxで再現しました。

また**Firefoxのみ**マウスで操作を行えば切り替えられる**時があります**。成功率は10回中6回くらいです。条件はよくわかりません。(Chromeだとそもそもメニュー要素をマウスオーバーしてもhover状態になりませんでした)

**Comment by qryxip** [comment]
- 横持ちでも多分あまり変わらず
- Firefoxだとタッチ操作でもメニューを出すところまではできる。Chromeだと多分メニューを出すことすら困難 (よくわからないがテキスト選択されるっぽい感触がする)

**Comment by Hiroshiba** [comment]
なるほどです、そもそもメニューを出すことすらできない感じなんですね！
bulmaというデザインフレームワークの更新をすると直るかもしれないので、ちょっと試してみたいと思います。

**Comment by Hiroshiba** [comment]
原因がわかりました、PR作ります
